services:
  lol_core:
    build:
      context: ../../league-of-letters
      dockerfile: Dockerfile
    env_file:
      - ./.env.lol-core
    ports:
      - "8080:3000"
    networks:
      - app-network    
    depends_on:
      - internal_dockerized_postgres
    environment:
      - PORT=3000
    restart: unless-stopped

  league_of_letters_actions:
    build:
      context: ../../actions-server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./.env.actions-server
    environment:
      - NODE_ENV=production
      - PORT=8080
    networks:
      - app-network

  internal_dockerized_postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: league-of-letters
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kaas}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "8082:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./postgres-backup:/backup
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d league-of-letters"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

networks:
  app-network:
    driver: bridge