version: '3.8'

services:
  nextjs-app:
    build:
      context: ../letter-league
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.actions-server
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  express-server:
    build:
      context: ../actions-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.letter-league-core
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: letter-league
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kaas}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./postgres-backup:/backup
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d letter-league"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

networks:
  app-network:
    driver: bridge