// LETTER GUESS POINTS
export const LETTER_CORRECTLY_GUESSED_WITHOUT_MISPLACE_POINTS: number = 5;
export const LETTER_MISPLACED_POINTS: number = 2;
export const LETTER_CORRECT_AFTER_MISPLACED_POINTS: number = 2;

// WORD GUESSED POINTS 
export const WORD_GUESSED_POINTS: number = 8;
export const WORD_GUESSED_FIRST_TRY_BONUS_POINTS = 12;
export const WORD_GUESSED_SECOND_TRY_BONUS_POINTS = 7;
